### ISSUE TITLE
Split task

### ISSUE THREAD

**Issue by newswangerd** [newswangerd/alexsandr_playbooks#4]
https://github.com/newswangerd/alexsandr_playbooks/blob/3c18a01766fd47e6b4e222b549e5817e8ac14ffe/Maybe_working.yml#L52

Split this into two tasks (one for the two RPMs and another for the php70 package). The first two RPMs install the repositories that contain the php70 package, so they need to be installed first.

**Comment by AlekKras** [comment]
implemented in test.yml
